<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Export_Message</name>
   <tag></tag>
   <elementGuidId>00e4929a-4429-4532-bed9-4ea1903c0969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;exportFormId:formSubmitMessage2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;exportFormId:formSubmitMessage2&quot;]</value>
   </webElementProperties>
</WebElementEntity>
